theme: jekyll-theme-minimal
url: "https://sap.how" # the base hostname & protocol
plugins:
  - jekyll-sitemap
permalink: /:categories/:title
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, articles.md, archive.md, google9163b442a553abe1.html, ewm/README.md] 

# Google Analytics
google_analytics: UA-45730869-6
