theme: jekyll-theme-minimal
url: "http://sap.how" # the base hostname & protocol
plugins:
  - jekyll-sitemap
collections_dir: articles
collection:
- ewm-development
collections:
  ewm-development:
    output: true
    permalink: /:collection/:name
